import { Router } from "express";
import { z } from "zod";
import { requireManager, type AuthRequest } from "./auth.js";
import { pool } from "./db.js";
import { asyncHandler, HttpError } from "./http.js";
import { createDeviceSecret, hashDeviceSecret } from "./deviceRoutes.js";
import { generateReportRows, rowsToCsv } from "./reportService.js";
import { nextCronRun } from "./domain/cron.js";
import { processDueReports } from "./reportScheduler.js";

export const advancedRouter = Router();
const uuid = z.string().uuid();
async function employeeForUser(userId: string, companyId: string): Promise<string> {
  const result = await pool.query<{ id: string }>("SELECT id FROM employees WHERE user_id=$1 AND company_id=$2 AND status<>'INACTIVE'", [userId, companyId]);
  if (!result.rows[0]) throw new HttpError(403, "No active employee profile is linked to this account");
  return result.rows[0].id;
}

// Device registry and privacy-preserving biometric mappings. Templates remain on the vendor device.
advancedRouter.get("/devices", requireManager, asyncHandler(async (request, response) => {
  const { companyId } = (request as AuthRequest).auth;
  const result = await pool.query(`SELECT d.id,d.name,d.vendor,d.serial_number AS "serialNumber",d.device_type AS "deviceType",d.active,d.last_seen_at AS "lastSeenAt",d.location_id AS "locationId",l.name AS location,
    (SELECT count(*)::int FROM biometric_identities b WHERE b.device_id=d.id AND b.active=true) AS "identityCount"
    FROM devices d LEFT JOIN locations l ON l.id=d.location_id WHERE d.company_id=$1 ORDER BY d.name`, [companyId]);
  response.json({ data: result.rows });
}));
advancedRouter.post("/devices", requireManager, asyncHandler(async (request, response) => {
  const input = z.object({ name:z.string().trim().min(2).max(100), vendor:z.string().trim().min(2).max(80), serialNumber:z.string().trim().min(2).max(120), deviceType:z.enum(["BIOMETRIC","FACE_TERMINAL","TURNSTILE","KIOSK"]), locationId:uuid.nullable().optional() }).parse(request.body);
  const { companyId, sub } = (request as AuthRequest).auth;
  const secret = createDeviceSecret();
  const result = await pool.query(`INSERT INTO devices(company_id,location_id,name,vendor,serial_number,device_type,api_key_hash) VALUES($1,$2,$3,$4,$5,$6,$7)
    RETURNING id,name,vendor,serial_number AS "serialNumber",device_type AS "deviceType",location_id AS "locationId",active`,
    [companyId,input.locationId??null,input.name,input.vendor,input.serialNumber,input.deviceType,hashDeviceSecret(secret)]);
  await pool.query(`INSERT INTO audit_logs(company_id,actor_user_id,action,entity_type,entity_id,next_value) VALUES($1,$2,'DEVICE_REGISTERED','DEVICE',$3,$4)`,[companyId,sub,result.rows[0].id,JSON.stringify(result.rows[0])]);
  response.status(201).json({ data: { ...result.rows[0], apiKey: secret } });
}));
advancedRouter.patch("/devices/:id", requireManager, asyncHandler(async (request,response)=>{
  const id=uuid.parse(request.params.id); const input=z.object({active:z.boolean()}).parse(request.body); const {companyId,sub}=(request as AuthRequest).auth;
  const result=await pool.query(`UPDATE devices SET active=$1 WHERE id=$2 AND company_id=$3 RETURNING id,active`,[input.active,id,companyId]);
  if(!result.rows[0])throw new HttpError(404,"Device not found");
  await pool.query(`INSERT INTO audit_logs(company_id,actor_user_id,action,entity_type,entity_id,next_value) VALUES($1,$2,'DEVICE_UPDATED','DEVICE',$3,$4)`,[companyId,sub,id,JSON.stringify(result.rows[0])]);
  response.json({data:result.rows[0]});
}));
advancedRouter.post("/devices/:id/identities",requireManager,asyncHandler(async(request,response)=>{
  const deviceId=uuid.parse(request.params.id);const input=z.object({employeeId:uuid,externalUserId:z.string().trim().min(1).max(160),biometricType:z.enum(["FACE","FINGERPRINT","CARD"])}).parse(request.body);const{companyId,sub}=(request as AuthRequest).auth;
  const result=await pool.query(`INSERT INTO biometric_identities(company_id,employee_id,device_id,external_user_id,biometric_type) SELECT $1,$2,d.id,$4,$5 FROM devices d JOIN employees e ON e.id=$2 AND e.company_id=$1 WHERE d.id=$3 AND d.company_id=$1 RETURNING id,employee_id AS "employeeId",external_user_id AS "externalUserId",biometric_type AS "biometricType"`,[companyId,input.employeeId,deviceId,input.externalUserId,input.biometricType]);
  if(!result.rows[0])throw new HttpError(400,"Invalid employee or device");
  await pool.query(`INSERT INTO audit_logs(company_id,actor_user_id,action,entity_type,entity_id,next_value) VALUES($1,$2,'BIOMETRIC_IDENTITY_LINKED','DEVICE',$3,$4)`,[companyId,sub,deviceId,JSON.stringify(result.rows[0])]);
  response.status(201).json({data:result.rows[0]});
}));
advancedRouter.get("/access-events",requireManager,asyncHandler(async(request,response)=>{const{companyId}=(request as AuthRequest).auth;const result=await pool.query(`SELECT a.id,a.event_type AS "eventType",a.occurred_at AS "occurredAt",a.confidence,a.liveness_passed AS "livenessPassed",a.external_user_id AS "externalUserId",d.name AS device,e.full_name AS employee,a.punch_id AS "punchId" FROM access_events a JOIN devices d ON d.id=a.device_id LEFT JOIN employees e ON e.id=a.employee_id WHERE a.company_id=$1 ORDER BY a.occurred_at DESC LIMIT 250`,[companyId]);response.json({data:result.rows});}));

// Availability and shift swap lifecycle.
advancedRouter.get("/me/availability",asyncHandler(async(request,response)=>{const{companyId,sub}=(request as AuthRequest).auth;const employeeId=await employeeForUser(sub,companyId);const result=await pool.query(`SELECT id,starts_at AS "startsAt",ends_at AS "endsAt",availability,note FROM employee_availability WHERE company_id=$1 AND employee_id=$2 AND ends_at>=now()-interval '30 days' ORDER BY starts_at`,[companyId,employeeId]);response.json({data:result.rows});}));
advancedRouter.post("/me/availability",asyncHandler(async(request,response)=>{const input=z.object({startsAt:z.string().datetime(),endsAt:z.string().datetime(),availability:z.enum(["AVAILABLE","UNAVAILABLE","PREFERRED"]),note:z.string().trim().max(300).optional()}).refine(v=>new Date(v.endsAt)>new Date(v.startsAt),{message:"End must be after start"}).parse(request.body);const{companyId,sub}=(request as AuthRequest).auth;const employeeId=await employeeForUser(sub,companyId);const result=await pool.query(`INSERT INTO employee_availability(company_id,employee_id,starts_at,ends_at,availability,note) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,starts_at AS "startsAt",ends_at AS "endsAt",availability,note`,[companyId,employeeId,input.startsAt,input.endsAt,input.availability,input.note??null]);response.status(201).json({data:result.rows[0]});}));
advancedRouter.delete("/me/availability/:id",asyncHandler(async(request,response)=>{const id=uuid.parse(request.params.id);const{companyId,sub}=(request as AuthRequest).auth;const employeeId=await employeeForUser(sub,companyId);const result=await pool.query(`DELETE FROM employee_availability WHERE id=$1 AND company_id=$2 AND employee_id=$3 RETURNING id`,[id,companyId,employeeId]);if(!result.rows[0])throw new HttpError(404,"Availability not found");response.json({data:{deleted:true}});}));
advancedRouter.get("/availability",requireManager,asyncHandler(async(request,response)=>{const{companyId}=(request as AuthRequest).auth;const from=z.string().date().optional().parse(request.query.from);const to=z.string().date().optional().parse(request.query.to);const result=await pool.query(`SELECT a.id,a.employee_id AS "employeeId",e.full_name AS employee,a.starts_at AS "startsAt",a.ends_at AS "endsAt",a.availability,a.note FROM employee_availability a JOIN employees e ON e.id=a.employee_id WHERE a.company_id=$1 AND a.ends_at>=COALESCE($2::date,CURRENT_DATE) AND a.starts_at<COALESCE($3::date,CURRENT_DATE+interval '30 days')+interval '1 day' ORDER BY a.starts_at`,[companyId,from??null,to??null]);response.json({data:result.rows});}));
advancedRouter.get("/shift-swaps",asyncHandler(async(request,response)=>{const{companyId,sub,role}=(request as AuthRequest).auth;const employeeId=role==="EMPLOYEE"?await employeeForUser(sub,companyId):null;const result=await pool.query(`SELECT w.id,w.shift_id AS "shiftId",w.requested_by AS "requestedBy",r.full_name AS requester,w.offered_to AS "offeredTo",o.full_name AS "offeredToName",w.accepted_by AS "acceptedBy",a.full_name AS "acceptedByName",w.reason,w.status,w.manager_note AS "managerNote",s.starts_at AS "startsAt",s.ends_at AS "endsAt" FROM shift_swaps w JOIN shifts s ON s.id=w.shift_id JOIN employees r ON r.id=w.requested_by LEFT JOIN employees o ON o.id=w.offered_to LEFT JOIN employees a ON a.id=w.accepted_by WHERE w.company_id=$1 AND ($2::uuid IS NULL OR w.requested_by=$2 OR w.offered_to=$2 OR w.status='OPEN') ORDER BY w.created_at DESC`,[companyId,employeeId]);response.json({data:result.rows});}));
advancedRouter.post("/me/shift-swaps",asyncHandler(async(request,response)=>{const input=z.object({shiftId:uuid,offeredTo:uuid.nullable().optional(),reason:z.string().trim().max(300).optional()}).parse(request.body);const{companyId,sub}=(request as AuthRequest).auth;const employeeId=await employeeForUser(sub,companyId);const result=await pool.query(`INSERT INTO shift_swaps(company_id,shift_id,requested_by,offered_to,reason) SELECT $1,s.id,$2,$3,$4 FROM shifts s WHERE s.id=$5 AND s.company_id=$1 AND s.employee_id=$2 AND s.status='PUBLISHED' AND s.starts_at>now() RETURNING id,status`,[companyId,employeeId,input.offeredTo??null,input.reason??null,input.shiftId]);if(!result.rows[0])throw new HttpError(400,"Only a future published shift can be swapped");response.status(201).json({data:result.rows[0]});}));
advancedRouter.post("/me/shift-swaps/:id/accept",asyncHandler(async(request,response)=>{const id=uuid.parse(request.params.id);const{companyId,sub}=(request as AuthRequest).auth;const employeeId=await employeeForUser(sub,companyId);const result=await pool.query(`UPDATE shift_swaps SET status='ACCEPTED',accepted_by=$1 WHERE id=$2 AND company_id=$3 AND status='OPEN' AND requested_by<>$1 AND (offered_to IS NULL OR offered_to=$1) RETURNING id,status`,[employeeId,id,companyId]);if(!result.rows[0])throw new HttpError(409,"This swap is no longer available");response.json({data:result.rows[0]});}));
advancedRouter.patch("/shift-swaps/:id/resolve",requireManager,asyncHandler(async(request,response)=>{const id=uuid.parse(request.params.id);const input=z.object({status:z.enum(["APPROVED","REJECTED"]),managerNote:z.string().trim().max(300).optional()}).parse(request.body);const{companyId,sub}=(request as AuthRequest).auth;const client=await pool.connect();try{await client.query("BEGIN");const swap=await client.query<{shift_id:string;accepted_by:string|null;status:string}>(`SELECT shift_id,accepted_by,status FROM shift_swaps WHERE id=$1 AND company_id=$2 FOR UPDATE`,[id,companyId]);if(!swap.rows[0])throw new HttpError(404,"Shift swap not found");if(input.status==="APPROVED"&&(!swap.rows[0].accepted_by||swap.rows[0].status!=="ACCEPTED"))throw new HttpError(409,"A replacement employee must accept first");if(input.status==="APPROVED")await client.query(`UPDATE shifts SET employee_id=$1,updated_at=now() WHERE id=$2 AND company_id=$3`,[swap.rows[0].accepted_by,swap.rows[0].shift_id,companyId]);const result=await client.query(`UPDATE shift_swaps SET status=$1,manager_note=$2,resolved_by=$3,resolved_at=now() WHERE id=$4 RETURNING id,status`,[input.status,input.managerNote??null,sub,id]);await client.query(`INSERT INTO audit_logs(company_id,actor_user_id,action,entity_type,entity_id,next_value) VALUES($1,$2,$3,'SHIFT_SWAP',$4,$5)`,[companyId,sub,`SHIFT_SWAP_${input.status}`,id,JSON.stringify(result.rows[0])]);await client.query("COMMIT");response.json({data:result.rows[0]});}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}));

// Recurring schedule templates and materialization.
advancedRouter.get("/recurring-schedules",requireManager,asyncHandler(async(request,response)=>{const{companyId}=(request as AuthRequest).auth;const result=await pool.query(`SELECT r.id,r.employee_id AS "employeeId",e.full_name AS employee,r.location_id AS "locationId",l.name AS location,r.weekdays,r.starts_at::text AS "startsAt",r.ends_at::text AS "endsAt",r.unpaid_break_minutes AS "unpaidBreakMinutes",r.grace_minutes AS "graceMinutes",r.effective_from AS "effectiveFrom",r.effective_until AS "effectiveUntil",r.active FROM recurring_schedules r JOIN employees e ON e.id=r.employee_id LEFT JOIN locations l ON l.id=r.location_id WHERE r.company_id=$1 ORDER BY e.full_name`,[companyId]);response.json({data:result.rows});}));
advancedRouter.post("/recurring-schedules",requireManager,asyncHandler(async(request,response)=>{const input=z.object({employeeId:uuid,locationId:uuid.nullable().optional(),weekdays:z.array(z.number().int().min(1).max(7)).min(1),startsAt:z.string().regex(/^\d{2}:\d{2}$/),endsAt:z.string().regex(/^\d{2}:\d{2}$/),unpaidBreakMinutes:z.number().int().min(0).max(480).default(60),graceMinutes:z.number().int().min(0).max(120).default(5),effectiveFrom:z.string().date(),effectiveUntil:z.string().date().nullable().optional()}).parse(request.body);const{companyId,sub}=(request as AuthRequest).auth;const result=await pool.query(`INSERT INTO recurring_schedules(company_id,employee_id,location_id,weekdays,starts_at,ends_at,unpaid_break_minutes,grace_minutes,effective_from,effective_until,created_by) SELECT $1,e.id,$3,$4,$5,$6,$7,$8,$9,$10,$11 FROM employees e WHERE e.id=$2 AND e.company_id=$1 RETURNING id`,[companyId,input.employeeId,input.locationId??null,input.weekdays,input.startsAt,input.endsAt,input.unpaidBreakMinutes,input.graceMinutes,input.effectiveFrom,input.effectiveUntil??null,sub]);if(!result.rows[0])throw new HttpError(400,"Invalid employee");response.status(201).json({data:result.rows[0]});}));
advancedRouter.post("/recurring-schedules/materialize",requireManager,asyncHandler(async(request,response)=>{const input=z.object({from:z.string().date(),to:z.string().date()}).refine(v=>v.to>=v.from,{message:"End must be on or after start"}).parse(request.body);const{companyId,sub}=(request as AuthRequest).auth;const result=await pool.query(`INSERT INTO shifts(company_id,employee_id,location_id,starts_at,ends_at,unpaid_break_minutes,grace_minutes,status,created_by)
    SELECT r.company_id,r.employee_id,r.location_id,(d.day+r.starts_at) AT TIME ZONE c.timezone,
      (d.day+r.ends_at+CASE WHEN r.ends_at<=r.starts_at THEN interval '1 day' ELSE interval '0 day' END) AT TIME ZONE c.timezone,
      r.unpaid_break_minutes,r.grace_minutes,'DRAFT',$4 FROM recurring_schedules r JOIN companies c ON c.id=r.company_id
      CROSS JOIN generate_series($2::date,$3::date,interval '1 day') d(day)
    WHERE r.company_id=$1 AND r.active=true AND extract(isodow FROM d.day)=ANY(r.weekdays) AND d.day::date>=r.effective_from AND (r.effective_until IS NULL OR d.day::date<=r.effective_until)
      AND NOT EXISTS(SELECT 1 FROM shifts s WHERE s.employee_id=r.employee_id AND s.starts_at=(d.day+r.starts_at) AT TIME ZONE c.timezone AND s.status<>'CANCELLED') RETURNING id`,[companyId,input.from,input.to,sub]);response.json({data:{created:result.rowCount??0}});}));

// Payroll policy, holidays, rates and benefits.
advancedRouter.get("/payroll-rules",requireManager,asyncHandler(async(request,response)=>{const{companyId}=(request as AuthRequest).auth;await pool.query(`INSERT INTO payroll_rules(company_id) VALUES($1) ON CONFLICT DO NOTHING`,[companyId]);const result=await pool.query(`SELECT overtime_multiplier::float AS "overtimeMultiplier",night_multiplier::float AS "nightMultiplier",holiday_multiplier::float AS "holidayMultiplier",night_starts_at::text AS "nightStartsAt",night_ends_at::text AS "nightEndsAt",pension_rate::float AS "pensionRate",social_tax_rate::float AS "socialTaxRate" FROM payroll_rules WHERE company_id=$1`,[companyId]);response.json({data:result.rows[0]});}));
advancedRouter.put("/payroll-rules",requireManager,asyncHandler(async(request,response)=>{const input=z.object({overtimeMultiplier:z.number().min(1).max(10),nightMultiplier:z.number().min(1).max(10),holidayMultiplier:z.number().min(1).max(10),nightStartsAt:z.string().regex(/^\d{2}:\d{2}$/),nightEndsAt:z.string().regex(/^\d{2}:\d{2}$/),pensionRate:z.number().min(0).max(100),socialTaxRate:z.number().min(0).max(100)}).parse(request.body);const{companyId,sub}=(request as AuthRequest).auth;const result=await pool.query(`INSERT INTO payroll_rules(company_id,overtime_multiplier,night_multiplier,holiday_multiplier,night_starts_at,night_ends_at,pension_rate,social_tax_rate) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(company_id) DO UPDATE SET overtime_multiplier=$2,night_multiplier=$3,holiday_multiplier=$4,night_starts_at=$5,night_ends_at=$6,pension_rate=$7,social_tax_rate=$8,updated_at=now() RETURNING *`,[companyId,input.overtimeMultiplier,input.nightMultiplier,input.holidayMultiplier,input.nightStartsAt,input.nightEndsAt,input.pensionRate,input.socialTaxRate]);await pool.query(`INSERT INTO audit_logs(company_id,actor_user_id,action,entity_type,entity_id,next_value) VALUES($1,$2,'PAYROLL_RULES_UPDATED','COMPANY',$1,$3)`,[companyId,sub,JSON.stringify(result.rows[0])]);response.json({data:result.rows[0]});}));
advancedRouter.get("/holidays",requireManager,asyncHandler(async(request,response)=>{const{companyId}=(request as AuthRequest).auth;const result=await pool.query(`SELECT id,holiday_date AS date,name,paid FROM holidays WHERE company_id=$1 ORDER BY holiday_date DESC`,[companyId]);response.json({data:result.rows});}));
advancedRouter.post("/holidays",requireManager,asyncHandler(async(request,response)=>{const input=z.object({date:z.string().date(),name:z.string().trim().min(2).max(120),paid:z.boolean().default(true)}).parse(request.body);const{companyId}=(request as AuthRequest).auth;const result=await pool.query(`INSERT INTO holidays(company_id,holiday_date,name,paid) VALUES($1,$2,$3,$4) ON CONFLICT(company_id,holiday_date) DO UPDATE SET name=$3,paid=$4 RETURNING id,holiday_date AS date,name,paid`,[companyId,input.date,input.name,input.paid]);response.status(201).json({data:result.rows[0]});}));
advancedRouter.delete("/holidays/:id",requireManager,asyncHandler(async(request,response)=>{const id=uuid.parse(request.params.id);const{companyId}=(request as AuthRequest).auth;await pool.query(`DELETE FROM holidays WHERE id=$1 AND company_id=$2`,[id,companyId]);response.json({data:{deleted:true}});}));
advancedRouter.post("/employees/:id/rates",requireManager,asyncHandler(async(request,response)=>{const employeeId=uuid.parse(request.params.id);const input=z.object({effectiveFrom:z.string().date(),hourlyRate:z.number().int().min(0),baseSalary:z.number().int().min(0)}).parse(request.body);const{companyId}=(request as AuthRequest).auth;const result=await pool.query(`INSERT INTO employee_rate_history(company_id,employee_id,effective_from,hourly_rate,base_salary) SELECT $1,e.id,$3,$4,$5 FROM employees e WHERE e.id=$2 AND e.company_id=$1 ON CONFLICT(employee_id,effective_from) DO UPDATE SET hourly_rate=$4,base_salary=$5 RETURNING id`,[companyId,employeeId,input.effectiveFrom,input.hourlyRate,input.baseSalary]);if(!result.rows[0])throw new HttpError(404,"Employee not found");response.status(201).json({data:result.rows[0]});}));
advancedRouter.post("/employees/:id/benefits",requireManager,asyncHandler(async(request,response)=>{const employeeId=uuid.parse(request.params.id);const input=z.object({name:z.string().trim().min(2).max(120),amount:z.number().int().min(0),taxable:z.boolean().default(true),startsOn:z.string().date().nullable().optional(),endsOn:z.string().date().nullable().optional(),active:z.boolean().default(true)}).parse(request.body);const{companyId}=(request as AuthRequest).auth;const result=await pool.query(`INSERT INTO employee_benefits(company_id,employee_id,name,amount,taxable,starts_on,ends_on,active) SELECT $1,e.id,$3,$4,$5,$6,$7,$8 FROM employees e WHERE e.id=$2 AND e.company_id=$1 ON CONFLICT(employee_id,name) DO UPDATE SET amount=$4,taxable=$5,starts_on=$6,ends_on=$7,active=$8 RETURNING id`,[companyId,employeeId,input.name,input.amount,input.taxable,input.startsOn??null,input.endsOn??null,input.active]);if(!result.rows[0])throw new HttpError(404,"Employee not found");response.status(201).json({data:result.rows[0]});}));

// Server-generated and schedulable reports.
advancedRouter.get("/reports",requireManager,asyncHandler(async(request,response)=>{const{companyId}=(request as AuthRequest).auth;const result=await pool.query(`SELECT id,name,report_type AS "reportType",format,schedule_cron AS "scheduleCron",recipients,filters,active,next_run_at AS "nextRunAt",last_run_at AS "lastRunAt" FROM report_definitions WHERE company_id=$1 ORDER BY created_at DESC`,[companyId]);response.json({data:result.rows});}));
advancedRouter.post("/reports",requireManager,asyncHandler(async(request,response)=>{const input=z.object({name:z.string().trim().min(2).max(120),reportType:z.enum(["ATTENDANCE","PAYROLL","AUDIT","ACCOUNTING"]),format:z.enum(["CSV","JSON"]),scheduleCron:z.string().trim().max(100).nullable().optional(),recipients:z.array(z.string().email()).default([]),filters:z.record(z.string(),z.unknown()).default({}),nextRunAt:z.string().datetime().nullable().optional()}).parse(request.body);const{companyId,sub}=(request as AuthRequest).auth;const cron=input.scheduleCron||null;if(cron)nextCronRun(cron);const next=input.nextRunAt??(cron?nextCronRun(cron).toISOString():null);const result=await pool.query(`INSERT INTO report_definitions(company_id,name,report_type,format,schedule_cron,recipients,filters,next_run_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,name,report_type AS "reportType",format,schedule_cron AS "scheduleCron",recipients,filters,next_run_at AS "nextRunAt",active`,[companyId,input.name,input.reportType,input.format,cron,input.recipients,JSON.stringify(input.filters),next,sub]);response.status(201).json({data:result.rows[0]});}));
advancedRouter.patch("/reports/:id",requireManager,asyncHandler(async(request,response)=>{const id=uuid.parse(request.params.id);const input=z.object({active:z.boolean()}).parse(request.body);const{companyId}=(request as AuthRequest).auth;const result=await pool.query(`UPDATE report_definitions SET active=$1 WHERE id=$2 AND company_id=$3 RETURNING id,active`,[input.active,id,companyId]);if(!result.rows[0])throw new HttpError(404,"Report not found");response.json({data:result.rows[0]});}));
advancedRouter.delete("/reports/:id",requireManager,asyncHandler(async(request,response)=>{const id=uuid.parse(request.params.id);const{companyId}=(request as AuthRequest).auth;await pool.query(`DELETE FROM report_definitions WHERE id=$1 AND company_id=$2`,[id,companyId]);response.json({data:{deleted:true}});}));
advancedRouter.post("/reports/run-due",requireManager,asyncHandler(async(request,response)=>{const{companyId}=(request as AuthRequest).auth;const processed=await processDueReports(companyId);response.json({data:{processed}});}));
advancedRouter.get("/reports/export/:type",requireManager,asyncHandler(async(request,response)=>{const type=z.enum(["attendance","payroll","audit","accounting"]).parse(request.params.type);const{companyId}=(request as AuthRequest).auth;const from=z.string().date().optional().parse(request.query.from);const to=z.string().date().optional().parse(request.query.to);const rows=await generateReportRows(companyId,type.toUpperCase() as "ATTENDANCE"|"PAYROLL"|"AUDIT"|"ACCOUNTING",{from,to});response.setHeader("Content-Type","text/csv; charset=utf-8");response.setHeader("Content-Disposition",`attachment; filename=atlas-${type}-${new Date().toISOString().slice(0,10)}.csv`);response.send(`\uFEFF${rowsToCsv(rows)}`);}));
